name: build kit.metis.science

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: GlistenSTAR/svelte-spectre

      - name: Install
        run: |
          npm install

      - name: Format
        run: |
          npm run format
      
      - name: URL redirects
        if: github.event_name == 'push'
        run: |
          Rscript -e 'pak::pkg_install("r-lib/urlchecker"); urlchecker::url_update()'
          git add -u && git commit -m 'Update links (GitHub Actions)' || echo "No link changes to commit"

      - name: Build
        run: |
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build
